name: CI

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo "testing secrets $SUPER_SECRET"
          if [["$SUPER_SECRET" == "server" ]];
          then
             echo "successful comparison"
          else
             echo "not successful comparison"
          fi
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env: 
          super_secret: ${{ secrets.NAMESPACE }}
          server1: ${{ secrets.server }}
          Greeting: Hello
        run: |
          echo "$Greeting my name"
          chmod +x test.sh
          echo "server value: $super_secret"
          if [[ "${{ secrets.NAMESPACE }}" == "server" ]];
          then
             echo "successful comparison"
          else
             echo "not successful comparison"
          fi
          if [ "a" == "a" ]
          then
             echo "Successful comparison if"
          fi
          sh test.sh
          pwd
          ls
          cat config
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create deployment --image ag14341/node-hello-app node-app1
