name: CI

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          chmod +x Generate_kubeconfig.sh
          chmod +x Generate_kubeconfig.sh
          sh Generate_kubeconfig.sh
          pwd
          ls
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create deployment --image ag14341/node-hello-app node-app1
