name: CI

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env: 
          super_secret: ${{ secrets.server }}
          server1: ${{ secrets.server }}
          Greeting: Hello
        run: |
          echo "$Greeting my name"
          chmod +x test.sh
          echo "server value: $super_secret"
          if [ $super_secert == "server" ]:
          then
             echo "successful comparison"
          fi
          sh test.sh
          pwd
          ls
          cat config
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create deployment --image ag14341/node-hello-app node-app1
